# title:    Cesar Antonio Gonzales Montes # your name (or website title) here
# logo: "/images/photo2.jpg?raw=true" # your photo (or logo) here
# description: > # your text below (remove <br> elements if you don't need line breaks)
# Mi objetivo principal es desarrollarm e profesionalm ente, evolucionar com o científico de datos y en el 
# campo financiero, de m odo que busco oportunidades que m e permitan hacerlo, al tiempo que trato de 
# alinearme completam ente con los objetivos de la empresa. 
# #   <br><br>
# Soy una persona que está acostum brada al trabajo bajo presión. También m e considero una persona 
# resolutiva, con buen ánimo y capaz de enfrentar problem as y salir de ellos fácilm ente.
#   <br><br>
#   <a href="https://www.linkedin.com/in/cesarg23/ " >View My LinkedIn Profile</a> 
  
# theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
title: Cesar Antonio Gonzales Montes # your name (or website title) here
logo: "/images/photo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Como Ingeniero de Aprendizaje Automático con experiencia en el sector 
  bancario, he adquirido sólidos conocimientos en inteligencia artificial, 
  análisis y procesamiento de datos, y cloud computing. Soy experto en 
  implementar modelos de aprendizaje automático, utilizando tecnologías 
  avanzadas para el procesamiento y almacenamiento de grandes volúmenes de 
  datos. Además, soy un miembro eficiente y proactivo en equipos de trabajo, 
  con habilidades demostradas para trabajar en entornos colaborativos y 
  metodologías ágiles. Mi pasión y dedicación en el campo de la ingeniería de 
  aprendizaje automático me impulsan a enfrentar nuevos desafíos y alcanzar niveles de excelencia aún mayores.
  <br><br>
  <a href="https://www.linkedin.com/in/cesarg23/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
