# title:    Cesar Antonio Gonzales Montes # your name (or website title) here
# logo: "/images/photo2.jpg?raw=true" # your photo (or logo) here
# description: > # your text below (remove <br> elements if you don't need line breaks)
# Mi objetivo principal es desarrollarm e profesionalm ente, evolucionar com o científico de datos y en el 
# campo financiero, de m odo que busco oportunidades que m e permitan hacerlo, al tiempo que trato de 
# alinearme completam ente con los objetivos de la empresa. 
# #   <br><br>
# Soy una persona que está acostum brada al trabajo bajo presión. También m e considero una persona 
# resolutiva, con buen ánimo y capaz de enfrentar problem as y salir de ellos fácilm ente.
#   <br><br>
#   <a href="https://www.linkedin.com/in/cesarg23/ " >View My LinkedIn Profile</a> 
  
# theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
title: Cesar Antonio Gonzales Montes # your name (or website title) here
logo: "/images/profile_pict.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  ML Engineer <br><br>
  UNMSM Economics Graduate <br><br>
  Email: rasecg23@gmail.com <br><br>

  <a href="https://www.linkedin.com/in/cesarg23/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
